"""Tests for src/dashboard.py — Dashboard.md generation."""
import json
from datetime import datetime, timezone
from pathlib import Path

import pytest

from setup_vault import setup_vault


@pytest.fixture
def vault(tmp_path):
    """Create a fully initialized vault for testing."""
    setup_vault(tmp_path)
    return tmp_path


# ---------------------------------------------------------------------------
# generate_dashboard
# ---------------------------------------------------------------------------


def test_generate_dashboard_returns_valid_markdown(vault):
    from src.dashboard import generate_dashboard

    md = generate_dashboard(vault)
    assert isinstance(md, str)
    assert "# Digital FTE Dashboard" in md
    assert "## System Status" in md
    assert "## Vault Overview" in md
    assert "*Auto-generated by Digital FTE*" in md


def test_generate_dashboard_has_frontmatter_with_updated_timestamp(vault):
    from src.dashboard import generate_dashboard

    md = generate_dashboard(vault)
    assert md.startswith("---\n")
    assert "updated:" in md


def test_vault_overview_counts_files_correctly(vault):
    """Folders with files should report the correct count."""
    from src.dashboard import generate_dashboard

    # Add 3 files to Needs_Action
    for i in range(3):
        (vault / "Needs_Action" / f"email-{i}.md").write_text(f"action {i}")

    # Add 1 file to Pending_Approval
    (vault / "Pending_Approval" / "plan-test.md").write_text("plan")

    md = generate_dashboard(vault)
    # Table row for Needs_Action should show 3
    assert "| Needs_Action | 3 |" in md
    # Table row for Pending_Approval should show 1
    assert "| Pending_Approval | 1 |" in md


def test_empty_vault_returns_zero_counts(vault):
    """An empty vault should show 0 for every folder."""
    from src.dashboard import generate_dashboard

    md = generate_dashboard(vault)
    # Every folder should show 0
    for folder in ["Inbox", "Needs_Action", "Plans", "Pending_Approval",
                    "Approved", "Done", "Logs", "Incoming_Files", "Rejected"]:
        assert f"| {folder} | 0 |" in md


def test_dashboard_includes_inbox_folder_count(vault):
    """Inbox folder should appear in the vault overview."""
    from src.dashboard import generate_dashboard

    (vault / "Inbox" / "new-email.md").write_text("inbox item")
    md = generate_dashboard(vault)
    assert "| Inbox | 1 |" in md


def test_pending_approvals_lists_files(vault):
    """Pending Approvals section should list files from Pending_Approval/."""
    from src.dashboard import generate_dashboard

    (vault / "Pending_Approval" / "plan-invoice-abc123.md").write_text("plan A")
    (vault / "Pending_Approval" / "plan-meeting-def456.md").write_text("plan B")

    md = generate_dashboard(vault)
    assert "## Pending Approvals" in md
    assert "plan-invoice-abc123.md" in md
    assert "plan-meeting-def456.md" in md


def test_pending_approvals_empty(vault):
    """When no pending approvals exist, section should say none."""
    from src.dashboard import generate_dashboard

    md = generate_dashboard(vault)
    assert "## Pending Approvals" in md
    assert "No pending approvals" in md


def test_recent_activity_reads_from_logs(vault):
    """Recent Activity should display entries from the latest Logs/*.json file."""
    from src.dashboard import generate_dashboard

    entries = [
        {
            "timestamp": "2026-02-17T10:30:00+00:00",
            "actor": "orchestrator",
            "action": "email_sent",
            "source": "plan-reply.md",
            "result": "reply_to:client@example.com",
        },
        {
            "timestamp": "2026-02-17T09:15:00+00:00",
            "actor": "orchestrator",
            "action": "plan_created",
            "source": "email-urgent.md",
            "result": "pending_approval:plan-urgent.md",
        },
    ]
    log_file = vault / "Logs" / "2026-02-17.json"
    log_file.write_text(json.dumps(entries, indent=2))

    md = generate_dashboard(vault)
    assert "## Recent Activity" in md
    assert "email_sent" in md
    assert "plan_created" in md


def test_recent_activity_empty(vault):
    """When no log files exist, Recent Activity should say no recent activity."""
    from src.dashboard import generate_dashboard

    md = generate_dashboard(vault)
    assert "## Recent Activity" in md
    assert "No recent activity" in md


def test_recent_activity_limits_to_10_entries(vault):
    """Recent Activity should show at most 10 entries."""
    from src.dashboard import generate_dashboard

    entries = []
    for i in range(15):
        entries.append({
            "timestamp": f"2026-02-17T{10+i:02d}:00:00+00:00",
            "actor": "orchestrator",
            "action": f"action_{i}",
            "source": f"file-{i}.md",
            "result": f"result_{i}",
        })
    log_file = vault / "Logs" / "2026-02-17.json"
    log_file.write_text(json.dumps(entries, indent=2))

    md = generate_dashboard(vault)
    # Should contain entries 5-14 (last 10), not entries 0-4
    assert "action_14" in md
    assert "action_5" in md
    assert "action_4" not in md


def test_system_status_active_when_items_to_process(vault):
    """System status should be Active when there are items in actionable folders."""
    from src.dashboard import generate_dashboard

    (vault / "Needs_Action" / "email-test.md").write_text("action")
    md = generate_dashboard(vault)
    assert "**Status:** Active" in md


def test_system_status_idle_when_nothing_to_process(vault):
    """System status should be Idle when no items to process."""
    from src.dashboard import generate_dashboard

    md = generate_dashboard(vault)
    assert "**Status:** Idle" in md


# ---------------------------------------------------------------------------
# update_dashboard
# ---------------------------------------------------------------------------


def test_update_dashboard_writes_file(vault):
    """update_dashboard should write Dashboard.md to the vault root."""
    from src.dashboard import update_dashboard

    update_dashboard(vault)
    dashboard = vault / "Dashboard.md"
    assert dashboard.exists()
    content = dashboard.read_text()
    assert "# Digital FTE Dashboard" in content


def test_update_dashboard_overwrites_existing(vault):
    """update_dashboard should overwrite an existing Dashboard.md."""
    from src.dashboard import update_dashboard

    (vault / "Dashboard.md").write_text("old content")
    update_dashboard(vault)
    content = (vault / "Dashboard.md").read_text()
    assert "old content" not in content
    assert "# Digital FTE Dashboard" in content


# ---------------------------------------------------------------------------
# setup_vault integration
# ---------------------------------------------------------------------------


def test_setup_vault_creates_inbox_folder(tmp_path):
    """setup_vault should create an Inbox/ folder."""
    setup_vault(tmp_path)
    assert (tmp_path / "Inbox").is_dir()


def test_setup_vault_creates_dashboard(tmp_path):
    """setup_vault should create Dashboard.md with initial content."""
    setup_vault(tmp_path)
    dashboard = tmp_path / "Dashboard.md"
    assert dashboard.exists()
    content = dashboard.read_text()
    assert "# Digital FTE Dashboard" in content


def test_setup_vault_does_not_overwrite_dashboard(tmp_path):
    """setup_vault should not overwrite existing Dashboard.md."""
    tmp_path.mkdir(parents=True, exist_ok=True)
    dashboard = tmp_path / "Dashboard.md"
    dashboard.write_text("# Custom Dashboard\nKeep this content.\n")
    setup_vault(tmp_path)
    content = dashboard.read_text()
    assert "Keep this content." in content
