"""Dashboard.md generator — produces a real-time vault summary for Obsidian."""
import json
from datetime import datetime, timezone
from pathlib import Path

# Folders to include in the vault overview table (in display order).
OVERVIEW_FOLDERS = [
    "Inbox",
    "Needs_Action",
    "Plans",
    "Pending_Approval",
    "Approved",
    "Done",
    "Logs",
    "Incoming_Files",
    "Rejected",
]

# Folders whose items count toward "things to process".
ACTIVE_FOLDERS = ["Inbox", "Needs_Action", "Pending_Approval", "Approved"]

MAX_RECENT_ENTRIES = 10


def _count_files(folder: Path) -> int:
    """Return the number of files (not dirs) in *folder*, 0 if missing."""
    if not folder.is_dir():
        return 0
    return sum(1 for f in folder.iterdir() if f.is_file())


def _items_to_process(vault_path: Path) -> int:
    """Count total files across folders that indicate work to do."""
    return sum(_count_files(vault_path / f) for f in ACTIVE_FOLDERS)


def _latest_log_file(logs_dir: Path) -> Path | None:
    """Return the most recent JSON log file, or None."""
    if not logs_dir.is_dir():
        return None
    log_files = sorted(logs_dir.glob("*.json"))
    return log_files[-1] if log_files else None


def _recent_activity(vault_path: Path) -> list[dict]:
    """Return the last MAX_RECENT_ENTRIES log entries from the latest log file."""
    log_file = _latest_log_file(vault_path / "Logs")
    if log_file is None:
        return []
    try:
        entries = json.loads(log_file.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return []
    return entries[-MAX_RECENT_ENTRIES:]


def _pending_approvals(vault_path: Path) -> list[tuple[str, str]]:
    """Return (filename, created_date) pairs for Pending_Approval/ files."""
    pa_dir = vault_path / "Pending_Approval"
    if not pa_dir.is_dir():
        return []
    results = []
    for f in sorted(pa_dir.iterdir()):
        if f.is_file():
            created = datetime.fromtimestamp(
                f.stat().st_mtime, tz=timezone.utc
            ).strftime("%Y-%m-%d")
            results.append((f.name, created))
    return results


def generate_dashboard(vault_path: Path) -> str:
    """Generate Dashboard.md content from current vault state."""
    now = datetime.now(timezone.utc).isoformat()
    total_active = _items_to_process(vault_path)
    status = "Active" if total_active > 0 else "Idle"

    lines: list[str] = []
    lines.append("---")
    lines.append(f"updated: {now}")
    lines.append("---")
    lines.append("")
    lines.append("# Digital FTE Dashboard")
    lines.append("")

    # System Status
    lines.append("## System Status")
    lines.append(f"**Status:** {status} | Items to process: {total_active}")
    lines.append("")

    # Vault Overview table
    lines.append("## Vault Overview")
    lines.append("| Folder | Items |")
    lines.append("|--------|-------|")
    for folder in OVERVIEW_FOLDERS:
        count = _count_files(vault_path / folder)
        lines.append(f"| {folder} | {count} |")
    lines.append("")

    # Pending Approvals
    lines.append("## Pending Approvals")
    approvals = _pending_approvals(vault_path)
    if approvals:
        for name, created in approvals:
            lines.append(f"- {name} (created: {created})")
    else:
        lines.append("No pending approvals.")
    lines.append("")

    # Recent Activity
    lines.append("## Recent Activity")
    activity = _recent_activity(vault_path)
    if activity:
        for entry in activity:
            ts = entry.get("timestamp", "")
            # Show just date + HH:MM
            short_ts = ts[:16].replace("T", " ") if len(ts) >= 16 else ts
            action = entry.get("action", "unknown")
            result = entry.get("result", "")
            lines.append(f"- [{short_ts}] {action}: {result}")
    else:
        lines.append("No recent activity.")
    lines.append("")

    lines.append("*Auto-generated by Digital FTE*")
    lines.append("")

    return "\n".join(lines)


def update_dashboard(vault_path: Path) -> None:
    """Write updated Dashboard.md to vault."""
    content = generate_dashboard(vault_path)
    (vault_path / "Dashboard.md").write_text(content, encoding="utf-8")
